### ISSUE TITLE
Unable to edit with MathLive after block is created

### ISSUE THREAD

**Issue by microBob** [AllanChain/logseq-live-math#1]
I love this plugin, however, I seem to be unable to edit inserted math. I can use `/math` to start writing an equation and use `[enter]` to complete it, but selecting the block again doesn't make the MathLive editor come back as demonstrated in the GIF.

Is this a bug, or am I using the plugin wrong? I use the default theme and only have bullet threadings and tabs as plugins.

**Comment by AllanChain** [comment]
Do you mean something like this?

![live-math-select-edit](https://github.com/AllanChain/logseq-live-math/assets/36528777/7914e69d-5001-4e17-9304-1aba74759ee1)

This looks like a bug in Logseq that sometimes selecting the block doesn't trigger the selection event. You have to click again on the selection to trigger the popup.

(I'll add this Logseq bug to README, and maybe report this to Logseq.)

**Comment by microBob** [comment]
Ah, yes looks like I do have to click again. Thank!

**Comment by arne-cl** [comment]
Dear Allan,

I have the same problem, but clicking on the selection does not make the popup appear again.
I'm using Logseq version 0.9.18. Is there anything I can do to debug this?

**Comment by AllanChain** [comment]
@arne-cl Logseq 0.9.18 has fixed that bug (https://github.com/logseq/logseq/issues/10106, https://github.com/logseq/logseq/pull/10113) and doesn't require an extra click. Please check if you are using the latest plugin, and also check the plugin settings in case you accidentally disabled this feature (post JSON from `Edit settings.json` if you are not certain).

**Comment by arne-cl** [comment]
Dear Allan,

thank you for your help! I didn't need to update or change any settings. It started working correctly after I rebooted my system.
