### ISSUE TITLE
我是windows11系统，输入$$ 后，自动出现公式输出系统，但是输入一个字符后logseq就直接卡死。

### ISSUE THREAD

**Issue by Hyc152** [AllanChain/logseq-live-math#12]
https://github.com/AllanChain/logseq-live-math/assets/53823339/446f558e-2787-4e76-9cb8-b8288ed61690

**Comment by AllanChain** [comment]
禁用其他插件之后还有这个问题吗？

**Comment by Hyc152** [comment]
没有了，和loseq-typewriter-mode
![image](https://github.com/AllanChain/logseq-live-math/assets/53823339/71159dab-4b28-49b2-be8f-f2670de52bf8)
 这个插件冲突。

**Comment by Hyc152** [comment]
嗯嗯，谢谢大佬，已经联系logseq-typewriter-mode 作者对插件进行优化
