### ISSUE TITLE
Typing parenthesis in text mode results in invalid Latex

### ISSUE THREAD

**Issue by chronos1970** [AllanChain/logseq-live-math#15]
### Platform
- **Logseq** [v0.10.0](https://github.com/logseq/logseq/releases/tag/0.10.0)
- **Live Math** v1.2.3
- No other plugins installed

### Problem
Trying to type parenthesis in text mode results in invalid Latex. This used to be a problem with old **MathLive** versions but was fixed a while ago in [ac2f460](https://github.com/arnog/mathlive/commit/ac2f460b3073a20ad6c83eb4f8b55141eaf583d9). Furthermore, the problem does not exist in the latest [MathLive demo](https://cortexjs.io/mathlive/demo/) (v0.97.4). Which is quite odd, since **Live Math** v1.2.3 should be using the same version.

### Screenshots
- Input
![image](https://github.com/AllanChain/logseq-live-math/assets/63144618/2a5dd411-cfa4-41ab-8f3c-f987d19f4a07)
- Output
![image](https://github.com/AllanChain/logseq-live-math/assets/63144618/2b71e940-946d-4b80-b51a-b0e12679a0ff)

**Comment by AllanChain** [comment]
> I wonder if the update didn't fully apply until I restarted.

Yes, I didn't work on this and many setting changes require a restart.

**Comment by chronos1970** [comment]
PS: I can confirm that the update hadn't fully applied actually. Since the new version has a new hamburger menu. On a side note, clicking the hamburger menu and selecting an option doesn't release the cursor so you will not be able to type in the math field afterwards.
![image](https://github.com/AllanChain/logseq-live-math/assets/63144618/6aa0e944-8e2a-4b44-b95c-d2b137168049)
