### ISSUE TITLE
[Bug] Floating window for inline math editing shrinks as you type

### ISSUE THREAD

**Issue by KekTuSx** [AllanChain/logseq-live-math#19]
### What happened?

The window for inline math editing shrinks as you type, until it eventually becomes a vertical line.

![math](https://github.com/AllanChain/logseq-live-math/assets/59769829/6e0f1e76-6664-4c14-907e-11a1eeb62683)

### Expected behaviour
The window does not get smaller when typing, instead it expands when the typed line reaches the on-screen keyboard button.

### Platform
This happens on both Windows 11 and Kubuntu

### Steps to reproduce
1. Install Logseq
2. Install Logseq Live Math plugin
3. Type /math, enter and type again.

### Logseq Version

0.10.1, 0.10.0

### Logseq Live Math Version

1.3.0

### Quick check

- [X] There is no existing issue about this bug

### Additional context

- No other plugins were enabled
- Default theme
- Default config

**Comment by AllanChain** [comment]
Thanks for reporting this! I didn't test with the newer MathLive before releasing...

https://github.com/AllanChain/logseq-live-math/releases/tag/v1.3.1 includes the fix.

**Comment by DawnPaladin** [comment]
I am still seeing this bug in Live Math 1.4.3 on MacOS.

**Comment by AllanChain** [comment]
@DawnPaladin I failed to reproduce this. Here are my steps:
- Open Logseq in a small (1/2 screen) size
- Open the math popup, type `a` until it fills the whole window
- Maximize the Logseq window
- Keep typing `a`

Result: the math popup keeps growing until it fills the whole window.

**Comment by DawnPaladin** [comment]
Here's a screen recording:

https://github.com/user-attachments/assets/b457794f-b29b-44ac-a5dd-be47a87cc92b

**Comment by AllanChain** [comment]
@DawnPaladin Thanks for the detailed report. This is fixed in 12985f4. The problem about resizing reflected in your screen recording is fixed in 817215f.

**Comment by DawnPaladin** [comment]
Fantastic! Thank you for the fix - I look forward to using it. How often do you publish new versions to the Logseq plugin marketplace?

**Comment by AllanChain** [comment]
> Fantastic! Thank you for the fix - I look forward to using it. How often do you publish new versions to the Logseq plugin marketplace?

I will public the new version on this weekend if I don't find new bugs introduced.
