### ISSUE TITLE
Examples of keybindings and inline shortcuts

### ISSUE THREAD

**Issue by YuvMilo** [AllanChain/logseq-live-math#2]
This plugin is amazing!

Just a single issue I'm having:  I couldn't manage to create any single keybinding even while looking at the provided link.

A possible solution would have been to put in the  setting JSON an example for possible keybindings and/or inline shortcuts commented out.

**Comment by AllanChain** [comment]
Thanks to point this out! I've added the examples

https://github.com/AllanChain/logseq-live-math/blob/19d7815879743f83dfba30c4527ed1b6986445a4/src/settings.ts#L42-L68

If you are still having problem to add your own keybindings, feel free to comment and reopen this issue.

**Comment by YuvMilo** [comment]
Hey,
First of all - Thanks! This is a great change done in extreme speed :) 
 I hope this is not asking for too much, but do you know if it's possible to add a keybinding that is made of two different parts?  For example, pressing "alt+g" followed by a "b" will add beta. (I'm trying to make the keybinding the same as another program that I'm using :) )
