### ISSUE TITLE
[Bug] Livemath doesn't render right inside a cloze

### ISSUE THREAD

**Issue by kinchahoy** [AllanChain/logseq-live-math#26]
### What happened?

A bullet point in Logseq like this doesn't render correctly 

$\det M$ = {{cloze  $e^{tr\log M}$}}

Either the content is shown correctly rendered but with the cloze deactivated, or the cloze works but the content does not render. This might be a bug for logseq to fix, if you think that's the case, I'm happy to ping them.

Thanks again for this plugin - it does exactly what I need it to!

### Logseq Version

0.10.7

### Logseq Live Math Version

latest

### Quick check

- [X] There is no existing issue about this bug

**Comment by AllanChain** [comment]
Thanks for using this plugin! However, I think this is a bug in Logseq (https://github.com/logseq/logseq/issues/5087) and I can do little thing about it.
