### ISSUE TITLE
Change are reverted when closing the window after focus lost

### ISSUE THREAD

**Issue by YuvMilo** [AllanChain/logseq-live-math#3]
When writing some piece of math. If one forgets to press enter before pressing (or moving) to another bullet the mathlive window stays open. This is not a big issue except exiting the window reverts the math block back to what it was prior entering mathlive (instead of leaving it as it is)

A (resonable) possible solution would be to close the mathlive window, saving the change, every time the user presses somewhere outside of the mathlive window.

**Comment by AllanChain** [comment]
Well, I've made a mistake. It turns out that 8a029de232351934a1600a12b2e7c107a81676bd was not a fix. The popup should not close when interacting with the title bar. It's not that easy to detect focus lost for the entire popup. I've reverted it and trying to find a better way to do that.

**Comment by YuvMilo** [comment]
It seems that it did do something useful: If one leaves some block before closing the mathlive window, and then closes the matlive window, the change that this person did (prior to leaving the block) remains, whereas prior to your commit it would have been reveted.

Therefore (in my very humble opinion) reverting the change might be a mistake. There are two different issues here (and it was an error on my part to only open one issue) - The change deletions after closing the window when focus was lost, and the automatic closing of the window itself. One requires detecting focus loss and the other does not (as far as I understand what the code could look like.)

(Tbh, I'm not sure what you mean by title bar so hopefully I'm not spamming this issue)

**Comment by AllanChain** [comment]
Sorry for the confusion. 8a029de232351934a1600a12b2e7c107a81676bd made it impossible to drag the popup if the math is edited. Therefore, such a fix for a small bug introduce another bigger bug. By reverting the commit, I don't mean that the commit is useless. I mean, I need to find a better way to do this.

As for this issue, I think the close button is a little ambiguous. Maybe I need to rework the UI and add separate buttons for reverting the math and closing the window.

PS: As a workaround for this issue, you can click on the math input field and press <kbd>Enter</kbd>.

**Comment by AllanChain** [comment]
The fix (a74dba3) is included in version 1.1.7. The close button now just closes the popup without modification. The revert feature is instead handled by a separate button. Feel free to reopen this issue (or create a new one) if you are still having a problem.
