### ISSUE TITLE
The shortcut keys used to toggle between math/text mode do not work.

### ISSUE THREAD

**Issue by Jimmy-Ma666** [AllanChain/logseq-live-math#8]
This plugin is great. I use it to take my math notes and it has helped me a lot.

There is a problem that troubles me. Mac version 13.4.1, logseq version 0.9.19, when I press the shortcut key option+shift+t, I cannot toggle math/text mode.

Thank you！

**Comment by AllanChain** [comment]
I currently don't have a MacBook. But I tried <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>T</kbd> on Linux, and it works as expected.

Could you elaborate what happens when you pressed <kbd>Shift</kbd>+<kbd>Option</kbd>+<kbd>T</kbd>, nothing happens or there is some conflict? Does it work if there is no other enabled plugins? And does it work on https://cortexjs.io/mathlive/demo/?

Meanwhile, you can use <kbd>"</kbd> to switch between math and text mode.

**Comment by Jimmy-Ma666** [comment]
Just nothing happens. It doesn't work if there is no other plugins either. It do works on mathlive demo.  

The " doesn't work in logseq either. Nothing happens either.

Thank you!

**Comment by Jimmy-Ma666** [comment]
I also found that, if in text mode, add any punctuation or space first, then press "or option+shift+t", I can switch to math mode.

**Comment by AllanChain** [comment]
Unfortunately, I failed to reproduce this. I just tried on macOS 14 and Logseq 0.9.19. Both `"` and `option+shift+T` work as expected, both entering and exiting math mode.

**Comment by Hyc152** [comment]
我是windows11系统，输入$$ 后，自动出现公式输出系统，但是输入一个字符后logseq就直接卡死。

**Comment by AllanChain** [comment]
@Hyc152 这看起来是新问题，可否新开一个 issue 详细讨论？
It's a different problem. Please open a new issue.

**Comment by Jimmy-Ma666** [comment]
It was found that the issue was caused by enabling smartMode. The problem no longer occurs after disabling it.

May I ask the author if you can share his Keybindings and Shortcuts configuration？ For typing physics and math formulas purposes.

Thanks a lot, the plugin has been very helpful.

**Comment by AllanChain** [comment]
@Jimmy-Ma666 Sharing the configs is a good idea! I don't have too much to share, but I've created a [GitHub Discussion thread](https://github.com/AllanChain/logseq-live-math/discussions/14) so that everyone can share their awesome configs.
