### ISSUE TITLE
[FR] Add a keyboard shortcut to trigger the plugin

### ISSUE THREAD

**Issue by proItheus** [AllanChain/logseq-live-math#9]
I feel typing `/m<Enter` every time I want to input math a bit cumbersome,  especially when it's just sth short like `$x\inX$`. 

I think we can add a shortcut, like `ctrl+m`? To trigger the math input like `\math`.

**Comment by AllanChain** [comment]
This can be implemented, but it doesn't feel necessary, at least for me. I prefer triggering using `$$`, which is as simple as `ctrl+m`. And if I'm typing short math, I'll do it without triggering the plugin.

Maybe there are some cases where you think `ctrl+m` is better than `$$`? Please share the feedback.

**Comment by proItheus** [comment]
It's indeed only slightly better I think, better in fewer keystroke. 

I prefer to have a unified interface when I want to type some math, so I'll use the trigger heavily, which is why I think it matters. And I believe when implemented, logseq will also automatically allow user to change this keybinding.

Anyway, it's upon you whether to implement it. That's just my usecase. 

And thanks for this wonderful plugin! It made my Latex writing experience a LOT more fluid, and now I'm writing all my course notes&reports&assignments using logseq+mathlive.

**Comment by AllanChain** [comment]
Released https://github.com/AllanChain/logseq-live-math/releases/tag/v1.2.1. I bound it to `ctrl+shift+m` by default, since `ctrl+m` minimized the Logseq window on Linux.
